### ISSUE TITLE
Script fails von Debian 8.5-minimal

### ISSUE THREAD

**Issue by Tsunayoshi** [alandmoore/debian_join_active_directory#1]
Hello,

in a minimal environment there is not aptitude, I had to use apt-get instead.

Thx for the Script

**Comment by alandmoore** [comment]
I see a few alternatives here:
- Let the user edit the `INSTALL_CMD` variable, as the script currently is, to suit the environment.  The downside is that users have to edit the script in some cases.
- Default to `apt` or `apt-get`, or whatever is  most ubiquitous.  The downside is this might create a conflict with whatever the user normally uses (do `aptitude` and `apt-get` still have problems when mixed?   There was a time when your dependency tracking would get hosed if you used both).
- Have a default, but read in some kind of shell variable or script argument to change the command.
- Autodetect what APT frontend exists?  Does Debian have a solution for this?

What do you think would be approrpriate?

**Comment by alandmoore** [comment]
Does the minimal install have just `apt`?  That might be the best choice.  I don't have a minimal install around.

**Comment by Tsunayoshi** [comment]
yeah apt works fine.

**Comment by alandmoore** [comment]
I changed it to `apt-get`.  After some research, it seems the issues between `apt-get` and aptitude are no longer around, and `apt` is not intended for scripts.

Should be fixed in  9c50822.
